name: Build and Deploy Node.js App

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    env:
      DB_HOST: 127.0.0.1
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    defaults:
      run:
        working-directory: ./webapp
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  

      - name: Install Dependencies
        run: npm install
        
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test_db;' -uroot -proot

      - name: Init MySQL
        run: node users.js
        
      - name: Run Integration Tests
        run: npm test 

  packer-format-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.0.0
        with:
          version: '1.10.0'

      - name: Packer init
        run: packer init *.pkr.hcl    

      - name: Packer fmt
        run: packer fmt -check -diff *.pkr.hcl

      - name: Packer validate
        run: packer validate *.pkr.hcl  

  build-artifact:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-artifact
          path: |
            webapp/
            webapp.service
            ops-agent-config.yaml

  build-image:
    needs: 
      - build-artifact
      - packer-format-validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download Node.js Artifact
        uses: actions/download-artifact@v4
        with:
          name: nodejs-artifact

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.0.0
        with:
          version: '1.10.0'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ vars.GCP_PROJECT_ID }}"
          credentials_json: '${{ secrets.GOOGLE_SA_CREDENTIALS }}'
          
      - name: Packer init
        run: packer init *.pkr.hcl 
        
      - name: Build Custom Image with Packer
        run: |
          packer build *.pkr.hcl
          IMAGE_NAME=$(jq -r '.builds[-1].artifact_id' packer-manifest.json | cut -d':' -f2)
          echo "IMAGE_NAME=$IMAGE_NAME" >> GITHUB_OUTPUT

  update-instance-template:
    needs: build-image
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ vars.GCP_PROJECT_ID }}"
          credentials_json: '${{ secrets.GOOGLE_SA_CREDENTIALS }}'

      - name: Config Parameters
        run: |
          TIMESTAMP=$(date +%s)
          INSTANCE_TEMPLATE_NAME="${{ vars.INSTANCE_TEMPLATE_NAME }}-$TIMESTAMP"
          IMAGE_NAME="${{ needs.build-image.outputs.image_name }}"
          KMS_KEY_SELF_LINK=projects/${{ vars.GCP_PROJECT_ID }}/locations/${{ vars.GCP_REGION }}/keyRings/WEBAPP_KEY_RING/cryptoKeys/VM_KEY
          NETWORK_SELF_LINK=https://www.googleapis.com/compute/v1/projects/${{ vars.GCP_PROJECT_ID }}/global/networks/my-vpc
          SUBNETWORK_SELF_LINK=https://www.googleapis.com/compute/v1/projects/${{ vars.GCP_PROJECT_ID }}/regions/${{ vars.GCP_REGION }}/subnetworks/webapp
          SERVICE_ACCOUNT_EMAIL=webapp-service-account@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Create New Instance Template
        run: |
          gcloud compute instance-templates create $INSTANCE_TEMPLATE_NAME \
            --machine-type=e2-small \
            --instance-template-region=${{ vars.GCP_REGION }} \
            --maintenance-policy=TERMINATE \
            --tags=web-servers \
            --disk="image=projects/${{ vars.GCP_PROJECT_ID }}/global/images/$IMAGE_NAME,size=100,type=pd-balanced" \
            --disk="kms-key=$KMS_KEY_SELF_LINK" \
            --network-interface="network=$NETWORK_SELF_LINK,subnet=$SUBNETWORK_SELF_LINK" \
            --metadata=startup-script='#!/bin/bash
            echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> /etc/environment
            echo "DB_USER=${{ vars.DB_USER }}" >> /etc/environment
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /etc/environment
            echo "DB_HOST=${{ vars.DB_HOST }}" >> /etc/environment' \
            --service-account=$SERVICE_ACCOUNT_EMAIL,scopes=cloud-platform

      - name: Update Managed Instance Group with New Template
        run: |
          gcloud compute instance-groups managed set-instance-template ${{ vars.INSTANCE_GROUP_NAME }} \
            --template=$INSTANCE_TEMPLATE_NAME\
            --region=${{ vars.GCP_REGION }}
    
      - name: Recreate Instances in Managed Instance Group
        run: |
          gcloud compute instance-groups managed rolling-action start-update ${{ vars.INSTANCE_GROUP_NAME }} \
            --version=template=$INSTANCE_TEMPLATE_NAME\
            --region=${{ vars.GCP_REGION }} \
            --type=proactive
  
      - name: Wait for MIG Refresh to Complete
        run: |
          gcloud compute instance-groups managed wait-until ${{ vars.INSTANCE_GROUP_NAME }} \
            --version-target-reached \
            --region=${{ vars.GCP_REGION }}

      