name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: test fail
      uses: exit 1
      

    # - name: Run Fail Test
    #   run: exit 1

