name: Packer Validation

on:
  pull_request:
    branches:
      - main
      
jobs:
  packer-format-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: '1.10.0'

      - name: Packer fmt
        run: packer fmt -check *.pkr.hcl

      - name: Packer validate
        run: packer validate *.pkr.hcl
