name: user.test CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    defaults:
      run:
        working-directory: ./webapp

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
        
    - name: Setup MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE test_db;' -uroot -proot

    - name: Init MySQL
      run: node users.js
      
    - name: Run Tests
      run: npm test

